secrets profile added

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -137,3 +137,55 @@ jobs:
             /home/runner/work
             !/home/runner/work/conda
             !/home/runner/work/singularity
+  test_profile_download:
+    name: nf-test with profiles needing mixcr license
+    # Only run on PRs from branches of nf-core/airrflow repository or on push if this is the nf-core dev branch (merged PRs)
+    # (GitHub secrets are not accessible for workflows from forks!)
+    if: "${{ github.event.pull_request.head.repo.full_name == 'nf-core/airrflow' || (github.event_name == 'push' && github.repository == 'nf-core/airrflow') }}"
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        NXF_VER:
+          - "23.04.0"
+          - "latest-everything"
+        profile: [
+          "test_mixcr_bulk",
+          "test_mixcr_sc",
+        ]
+
+    steps:
+      - name: Check out pipeline code
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
+
+      - name: Install Nextflow
+        uses: nf-core/setup-nextflow@v1
+        with:
+          version: "${{ matrix.NXF_VER }}"
+
+      - name: Disk space cleanup
+        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
+
+      - name: Install nf-test
+        uses: nf-core/setup-nf-test@v1
+        with:
+          version: ${{ env.NFT_VER }}
+
+      - name: Run nf-test
+        env:
+          NCBI_EMAIL: ${{ secrets.MIXCR_LICENSE }}
+        run: |
+          nextflow secrets set MIXCR_LICENSE ${{ secrets.MIXCR_LICENSE }}
+          nf-test test --tag ${{ matrix.profile }} --profile ${{ matrix.profile }},docker --junitxml=test.xml --verbose
+
+      - name: Output log on failure
+        if: failure()
+        run: |
+          sudo apt install bat > /dev/null
+          batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/output/pipeline_info/software_versions.yml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: "*.xml"
